# Generated by Django 5.2.3 on 2025-06-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(default='qqq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(default='qqq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(default='www'),
            preserve_default=False,
        ),
    ]
