# Generated by Django 5.2.3 on 2025-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_vacancy_conditions_vacancy_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='isActive',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
