# Generated by Django 5.2.3 on 2025-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_vacancy_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='interviews',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
