# Generated by Django 5.2.3 on 2025-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_vacancy_interviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='interviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
