# Generated by Django 5.2.3 on 2025-07-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_vacancy_interviews_alter_vacancy_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-id'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='interviews',
            field=models.IntegerField(default=0, verbose_name='Пройдено собеседований'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Отображается'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
