# Generated by Django 5.2.3 on 2025-07-09 19:02

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_vacancy_options_alter_vacancy_conditions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_pairs', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Словарь вопросов и ответов в формате {'вопрос': 'ответ'}", verbose_name='Вопросы и ответы')),
                ('score_percentage', models.FloatField(default=0, help_text='Процент правильных/хороших ответов (0-100)', verbose_name='Процент результата')),
                ('assessment_text', models.TextField(blank=True, help_text='Текстовая оценка от нейросети/HR', null=True, verbose_name='Текстовая оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to='employee.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Результат собеседования',
                'verbose_name_plural': 'Результаты собеседований',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
