# Generated by Django 5.2.3 on 2025-07-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_interviewresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresult',
            name='updated_at',
        ),
    ]
