# Generated by Django 5.2.3 on 2025-07-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_interviewresult_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewresult',
            unique_together=set(),
        ),
    ]
