# Generated by Django 5.2.3 on 2025-07-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_interviewresult_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='score_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Процент правильных/хороших ответов (0-100)', max_digits=5, verbose_name='Процент результата'),
        ),
    ]
