# Generated by Django 5.2.3 on 2025-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_interviewresult_score_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='score_percentage',
            field=models.FloatField(default=0.0, help_text='Процент правильных/хороших ответов (0-100)', verbose_name='Процент результата'),
        ),
    ]
