# Generated by Django 5.2.3 on 2025-07-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_interviewresult_score_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='interviews',
        ),
    ]
