# Generated by Django 5.2.3 on 2025-07-12 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_remove_vacancy_interviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
